spring.datasource.url=jdbc:mysql://localhost:3306/servicefinder
spring.datasource.username=root
spring.datasource.password=Asha530680@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect